[build]
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  included_files = ["services/**", "config/**"]
  external_node_modules = ["firebase-admin"]


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = true

[build.environment]
  NODE_VERSION = "18"